"""Shared fixtures for open_wave_analyzer regression tests."""

import json
import subprocess
import sys
from pathlib import Path, PureWindowsPath
from types import SimpleNamespace

import pytest

VERIFY_DIR = Path(__file__).resolve().parent
SCRIPT = VERIFY_DIR.parent / 'open_wave_analyzer.py'
WAVEFORMS_DIR = VERIFY_DIR / 'waveforms'


def load_manifest():
    """Load the waveform manifest generated by gen_waveforms.py."""
    manifest_path = WAVEFORMS_DIR / 'manifest.json'
    if not manifest_path.exists():
        return []
    return json.loads(manifest_path.read_text())


def run_analyzer(args, timeout=30):
    """Run open_wave_analyzer.py with given arguments, return completed process."""
    cmd = [sys.executable, '-S', str(SCRIPT)] + [str(a) for a in args]
    return subprocess.run(
        cmd, capture_output=True, text=True, timeout=timeout
    )


def run_analyzer_json(args, timeout=30):
    """Run with --json and parse output."""
    r = run_analyzer(['--json'] + args, timeout=timeout)
    if r.returncode != 0:
        return None, r.stderr
    try:
        return json.loads(r.stdout.strip()), None
    except json.JSONDecodeError:
        return None, r.stdout[:500]


def normalize_info(info):
    """Normalize info output for comparison - remove fields that differ by format."""
    # Fields that may differ between VCD and FST
    for key in ['file', 'size_bytes', 'signal_count', 'reference_count',
                'synthesized_buses', 'comments', 'scopes']:
        info.pop(key, None)
    # Normalize var_types - FST may use different type names
    if 'var_types' in info:
        info['var_types'] = {k: v for k, v in sorted(info['var_types'].items())
                             if v > 0}
    return info


def normalize_list_output(data):
    """Normalize list output: sort by path, remove format-specific fields."""
    signals = data.get('signals', [])
    for s in signals:
        s.pop('id', None)
        s.pop('synthesized', None)
        s.pop('raw_bits', None)
    signals.sort(key=lambda x: x['path'])
    return data


def normalize_dump_output(data):
    """Normalize dump events: sort by time+path."""
    events = data.get('events', [])
    for e in events:
        e.pop('width', None)
        e.pop('type', None)
    events.sort(key=lambda x: (x['time_ticks'], x['path']))
    return data


def normalize_snapshot_output(data):
    """Normalize snapshot signals."""
    signals = data.get('signals', [])
    for s in signals:
        s.pop('width', None)
        s.pop('type', None)
        s.pop('undefined', None)
    signals.sort(key=lambda x: x['path'])
    return data


def normalize_summary_output(data):
    """Normalize summary rows."""
    rows = data.get('rows', [])
    for r in rows:
        r.pop('width', None)
        r.pop('type', None)
        r.pop('_width', None)
        r.pop('_type', None)
    rows.sort(key=lambda x: x['path'])
    return data


def normalize_compare_output(data):
    """Normalize compare diffs."""
    diffs = data.get('diffs', [])
    for d in diffs:
        d.pop('width', None)
        d.pop('type', None)
    diffs.sort(key=lambda x: x['path'])
    return data


def normalize_search_output(data):
    """Normalize search results."""
    mode = data.get('mode', 'interval')
    key = 'segments' if mode == 'segment' else 'intervals' if mode == 'interval' else 'events'
    results = data.get(key, [])
    for r in results:
        r.pop('meta', None)
    return data


def ns(**kwargs):
    """Build a SimpleNamespace for programmatic command calls."""
    defaults = dict(json=False, verbose=False, limit=None, filter=None,
                    begin=None, end=None, at=None, condition=None,
                    show=None, changed=None)
    defaults.update(kwargs)
    return SimpleNamespace(**defaults)


# ===================================================================
# Pytest fixtures
# ===================================================================

def _manifest():
    return load_manifest()


def pytest_generate_tests(metafunc):
    """Parametrize tests with all waveform pairs from the manifest."""
    if 'wave_pair' in metafunc.fixturenames:
        manifest = _manifest()
        # Resolve paths relative to local waveforms dir (manifest may have
        # absolute paths from the machine that generated it).
        resolved = []
        for m in manifest:
            vcd_name = PureWindowsPath(m['vcd']).name
            fst_name = PureWindowsPath(m['fst']).name
            vcd_path = WAVEFORMS_DIR / vcd_name
            fst_path = WAVEFORMS_DIR / fst_name
            if vcd_path.exists() and fst_path.exists():
                resolved.append({
                    'name': m['name'],
                    'vcd': str(vcd_path),
                    'fst': str(fst_path),
                })
        ids = [m['name'] for m in resolved]
        metafunc.parametrize('wave_pair', resolved, ids=ids)
